version: 2
jobs:
  dashing:
    docker:
      - image: ros:dashing-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y build-essential cmake python3-colcon-common-extensions python3-rosdep python3-pip
            pip3 install --upgrade pytest
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            mkdir -p src/image_pipeline && mv `find -maxdepth 1 -not -name . -not -name src` src/image_pipeline/
            rosdep update
            rosdep install -y --from-paths . --ignore-src
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            colcon build --parallel-workers 2
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            colcon test --parallel-workers 2
            colcon test-result

workflows:
  version: 2
  ros_build:
    jobs:
      - dashing
