version: 2
jobs:
  noetic:
    docker:
      - image: jwhitleywork/ros:noetic-ros-base-focal
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            apt-get update -q
            rosdep update
            rosdep install -y --from-paths . --ignore-src
            catkin_init_workspace
      - run:
          name: Build
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests -j4
            catkin_test_results
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - noetic
