version: 2
jobs:
  crystal:
    docker:
      - image: ros:crystal-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y python-catkin-tools
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            mkdir -p src/image_pipeline && mv `find -maxdepth 1 -not -name . -not -name src` src/image_pipeline/
            rosdep update
            rosdep install -y --from-paths . --ignore-src
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            colcon build --no-status -j4
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            colcon test -j4
            colcon test-result --test-result-base build/image_pipeline

workflows:
  version: 2
  ros_build:
    jobs:
      - crystal
